import type { Metadata } from "next";
import { Geist, Geist_Mono, Iceberg } from "next/font/google"; // Import Iceberg font
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const iceberg = Iceberg({ // Add Iceberg font
  variable: "--font-iceberg",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${iceberg.variable} antialiased`} // Include Iceberg font
      >
        {children}
      </body>
    </html>
  );
}
